specVersion: 0.0.1
description: ''
repository: ''
schema: ./schema.graphql
network:
  endpoint: wss://polkadot.api.onfinality.io/public-ws
  dictionary: https://api.subquery.network/sq/subquery/dictionary-polkadot
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 6000000
    mapping:
      handlers:
        - handler: handleSumReward
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Reward          
        - handler: handleSumRewarded
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Rewarded                       
        - handler: handleStakingReward
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Rewarded     
        - handler: handleStakingRewarded
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Rewardeded                      